---
- hosts: all
  become: true
  tasks:
  - name: Install snmpd on CentOS
    yum:
      name: net-snmp
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"
  - name: Install snmpd on Debian
    apt:
      name: snmpd
      state: latest
    when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"
  - name: Enable snmpd
    service:
      name: snmpd
      enabled: yes
      state: started
  - name: Download snmpd config file
    get_url:
      url: http://192.168.1.88/snmpd.conf
      dest: /etc/snmp/snmpd.conf
  - name: Restart snmpd
    service:
      name: snmpd
      state: restarted    
